"""Declarative settings panels mirroring sunnypilot BIG UI (15 panels)."""

from __future__ import annotations

from typing import Any

# Widget types: bool, int, choice, readonly, action, section, html, subpanel_ref

PANELS: list[dict[str, Any]] = [
  {
    "id": "device",
    "title": "Device",
    "custom": "device",
    "widgets": [
      {"type": "readonly", "param": "DongleId", "label": "Dongle ID"},
      {"type": "separator"},
      {"type": "readonly", "param": "HardwareSerial", "label": "Serial"},
      {"type": "separator"},
      {"type": "action", "action": "pair_device", "label": "Pair Device", "button": "PAIR",
       "desc": "Pair your device with comma connect (connect.comma.ai) and claim your comma prime offer.",
       "hide_when_paired": True},
      {"type": "separator"},
      {"type": "action", "action": "reset_calibration", "label": "Reset Calibration", "button": "RESET",
       "desc": "sunnypilot requires the device to be mounted within 4° left or right and within 5° up or 9° down.",
       "dynamic_desc": "calibration",
       "confirm": "Are you sure you want to reset calibration?"},
      {"type": "separator"},
      {"type": "custom", "custom": "device_language"},
      {"type": "separator"},
      {"type": "custom", "custom": "chestnut_status"},
      {"type": "multiple_button", "param": "DeviceBootMode", "label": "Wake Up Behavior",
       "buttons": ["Default", "Offroad"], "layout": "inline",
       "desc": "Controls state of the device after boot/sleep.\n\nDefault: Device will boot/wake-up normally & will be ready to engage.\nOffroad: Device will be in Always Offroad mode after boot/wake-up."},
      {"type": "separator"},
      {"type": "option", "param": "MaxTimeOffroad", "label": "Max Time Offroad",
       "desc": "Device will automatically shutdown after set time once the engine is turned off.\n(30h is the default)",
       "min": 0, "max": 11, "step": 1, "layout": "inline",
       "value_map": {"0": 0, "1": 5, "2": 10, "3": 15, "4": 30, "5": 60, "6": 120, "7": 180, "8": 300, "9": 600, "10": 1440, "11": 1800}},
      {"type": "dual_button",
       "left": {"label": "Quiet Mode", "param": "QuietMode", "toggle": True},
       "right": {"label": "Driver Camera Preview", "action": "driver_view", "offroad_only": True,
                 "desc": "Enable driver camera preview in Web UI while offroad. Turn off before driving."}},
      {"type": "dual_button",
       "left": {"label": "", "hidden": True},
       "right": {"label": "Onroad Preview", "action": "onroad_preview", "offroad_only": True}},
      {"type": "dual_button",
       "left": {"label": "Regulatory", "action": "open_regulatory", "offroad_only": True},
       "right": {"label": "Training Guide", "action": "open_training", "offroad_only": True}},
      {"type": "dual_button",
       "left": {"label": "Onroad Uploads", "param": "OnroadUploads", "toggle": True},
       "right": {"label": "Reset Settings", "action": "reset_all_params", "offroad_only": True, "confirm_twice": True}},
      {"type": "custom", "custom": "always_offroad"},
      {"type": "dual_button",
       "left": {"label": "Reboot", "action": "reboot"},
       "right": {"label": "Power Off", "action": "shutdown", "offroad_only": True, "hide_when_onroad": True}},
    ],
  },
  {
    "id": "imu_calibration",
    "title": "IMU Calibration",
    "custom": "imu_calibration",
    "widgets": [
      {"type": "bool", "param": "ImuCalibrationEnabled", "label": "Use IMU Calibration",
       "desc_i18n": "UseIMUCalibrationDescription",
       "needs_cycle": True},
      {"type": "action", "action": "imu_calibration_start", "label": "Start IMU Calibration", "button": "START",
       "desc_i18n": "StartIMUCalibrationDescription",
       "visible_if": {"param": "ImuCalibrationEnabled", "eq": "1"}},
      {"type": "action", "action": "imu_calibration_reset", "label": "Reset IMU Calibration", "button": "RESET",
       "desc_i18n": "ResetIMUCalibrationDescription",
       "confirm": "Are you sure you want to clear the IMU calibration and switch back to stock calibration?",
       "visible_if": {"param": "ImuCalibrationEnabled", "eq": "1"}},
    ],
  },
  {
    "id": "network",
    "title": "Network",
    "custom": "network",
    "widgets": [
      {"type": "subpanel", "target": "network__advanced", "label": "Advanced Network", "button": "ADVANCED"},
    ],
  },
  {
    "id": "sunnylink",
    "title": "sunnylink",
    "custom": "sunnylink",
    "widgets": [],
  },
  {
    "id": "toggles",
    "title": "Toggles",
    "widgets": [
      {"type": "bool", "param": "OpenpilotEnabledToggle", "label": "Enable sunnypilot", "needs_cycle": True,
       "icon": "selfdrive/assets/icons/chffr_wheel.png",
       "desc": "Use the sunnypilot system for adaptive cruise control and lane keep driver assistance. Your attention is required at all times to use this feature."},
      {"type": "bool", "param": "ExperimentalMode", "label": "Experimental Mode", "confirm_experimental": True,
       "capability": "longitudinal",
       "icon": "selfdrive/assets/icons/experimental_white.png",
       "icon_active": "selfdrive/assets/icons/experimental.png"},
      {"type": "bool", "param": "DisengageOnAccelerator", "label": "Disengage on Accelerator Pedal",
       "icon": "selfdrive/assets/icons/disengage_on_accelerator.png",
       "desc": "When enabled, pressing the accelerator pedal will disengage sunnypilot."},
      {"type": "multiple_button", "param": "LongitudinalPersonality", "label": "Driving Personality",
       "layout": "stacked", "capability": "longitudinal",
       "icon": "selfdrive/assets/icons/speed_limit.png",
       "buttons": ["Aggressive", "Standard", "Relaxed"],
       "desc": "Standard is recommended. In aggressive mode, sunnypilot will follow lead cars closer and be more aggressive with the gas and brake. In relaxed mode sunnypilot will stay further away from lead cars. On supported cars, you can cycle through these personalities with your steering wheel distance button."},
      {"type": "bool", "param": "IsLdwEnabled", "label": "Enable Lane Departure Warnings",
       "icon": "selfdrive/assets/icons/warning.png",
       "desc": "Receive alerts to steer back into the lane when your vehicle drifts over a detected lane line without a turn signal activated while driving over 31 mph (50 km/h)."},
      {"type": "bool", "param": "DisableDM", "label": "Disable Driver Monitoring", "needs_cycle": True,
       "icon": "selfdrive/assets/icons/monitoring.png",
       "desc": "Disable driver monitoring (no cabin camera required). Similar to LITE mode."},
      {"type": "bool", "param": "AlwaysOnDM", "label": "Always-On Driver Monitoring",
       "icon": "selfdrive/assets/icons/monitoring.png",
       "hide_if": {"param": "DisableDM", "eq": "1"},
       "desc": "The driver monitoring system can be toggled on/off, but long-term activation is recommended"},
      {"type": "multiple_button", "param": "DistractionDetectionLevel", "label": "Distraction Detection Level",
       "layout": "stacked",
       "icon": "selfdrive/assets/icons/monitoring.png",
       "buttons": ["Strict", "Moderate", "Lenient"],
       "visible_if": {"param": "AlwaysOnDM", "eq": "1"},
       "hide_if": {"param": "DisableDM", "eq": "1"},
       "desc": "Set how sensitive the driver distraction detection should be. Strict: Very sensitive, warns on minor distractions. Moderate: Balanced between sensitivity and false positives. Lenient: Only alerts on clear distractions."},
      {"type": "bool", "param": "RecordFront", "label": "Record and Upload Driver Camera", "needs_cycle": True,
       "icon": "selfdrive/assets/icons/monitoring.png",
       "hide_if": {"param": "DisableDM", "eq": "1"},
       "desc": "Upload data from the driver facing camera and help improve the driver monitoring algorithm."},
      {"type": "bool", "param": "RecordAudio", "label": "Record and Upload Microphone Audio", "needs_cycle": True,
       "icon": "selfdrive/assets/icons/microphone.png",
       "desc": "Record and store microphone audio while driving. The audio will be included in the dashcam video in comma connect."},
      {"type": "bool", "param": "SpDevBeep", "label": "Beeper Feedback", "lite_only": True, "needs_cycle": True,
       "icon": "selfdrive/assets/icons/warning.png",
       "desc": "Use the GPIO beeper for engage/disengage sounds on Lite hardware without a speaker."},
      {"type": "bool", "param": "IsMetric", "label": "Use Metric System",
       "icon": "selfdrive/assets/icons/metric.png",
       "desc": "Display speed in km/h instead of mph."},
    ],
  },
  {
    "id": "software",
    "title": "Software",
    "custom": "software",
    "widgets": [
      {"type": "action", "action": "uninstall", "label": "Uninstall", "button": "UNINSTALL",
       "confirm": "Are you sure you want to uninstall?", "offroad_only": True},
      {"type": "custom", "custom": "webui_update"},
      {"type": "bool", "param": "DisableUpdates", "label": "Disable Updates",
       "visible_if": {"param": "ShowAdvancedControls", "eq": "1"}, "offroad_only": True},
    ],
  },
  {
    "id": "models",
    "title": "Models",
    "custom": "models",
    "widgets": [
      {"type": "action", "action": "models_sync", "label": "Refresh Model List", "button": "REFRESH"},
      {"type": "action", "action": "models_clear_cache", "label": "Clear Model Cache", "button": "CLEAR",
       "confirm": "This will delete ALL downloaded models from the cache except the currently active model. Are you sure?",
       "confirm_button": "Clear Cache"},
      {"type": "bool", "param": "LaneTurnDesire", "label": "Use Lane Turn Desires",
       "desc": "If you're driving at 20 mph (32 km/h) or below and have your blinker on, the car will plan a turn in that direction at the nearest drivable path. This prevents situations (like at red lights) where the car might plan the wrong turn direction."},
      {"type": "option", "param": "LaneTurnValue", "label": "Adjust Lane Turn Speed",
       "min": 500, "max": 2000, "step": 100, "label_format": "lane_turn_speed",
       "desc": "Set the maximum speed for lane turn desires. Default is 19 mph.",
       "visible_if": {"param": "LaneTurnDesire", "eq": "1"},
       "advanced_if": {"param": "ShowAdvancedControls", "eq": "1"}},
      {"type": "bool", "param": "LagdToggle", "label": "Live Learning Steer Delay",
       "desc": "Enable this for the car to learn and adapt its steering response time. Disable to use a fixed steering response time. Keeping this on provides the stock openpilot experience."},
      {"type": "option", "param": "LagdToggleDelay", "label": "Adjust Software Delay",
       "min": 5, "max": 50, "step": 1, "label_format": "lagd_delay",
       "desc": "Adjust the software delay when Live Learning Steer Delay is toggled off. The default software delay value is 0.2",
       "visible_if": {"param": "LagdToggle", "eq": "0"},
       "advanced_if": {"param": "ShowAdvancedControls", "eq": "1"}},
      {"type": "option", "param": "CameraOffset", "label": "Adjust Camera Offset",
       "min": -35, "max": 35, "step": 1, "label_format": "camera_offset",
       "desc": "Virtually shift camera's perspective to move model's center to Left(+ values) or Right (- values)",
       "visible_if": {"state": "custom_model_active"}},
    ],
  },
  {
    "id": "steering",
    "title": "Steering",
    "widgets": [
      {"type": "bool", "param": "Mads", "label": "Modular Assistive Driving System (MADS)", "offroad_only": True,
       "desc": "Enable the beloved MADS feature. Disable toggle to revert back to stock sunnypilot engagement/disengagement."},
      {"type": "subpanel", "target": "steering__mads", "label": "Customize MADS", "button": "CUSTOMIZE",
       "requires": {"param": "Mads", "eq": "1"}, "offroad_only": True},
      {"type": "separator"},
      {"type": "subpanel", "target": "steering__lane_change", "label": "Customize Lane Change", "button": "CUSTOMIZE"},
      {"type": "separator"},
      {"type": "bool", "param": "BlinkerPauseLateralControl", "label": "Pause Lateral Control with Blinker",
       "desc": "Pause lateral control with blinker when traveling below the desired speed selected."},
      {"type": "option", "param": "BlinkerMinLateralControlSpeed", "label": "Minimum Speed to Pause Lateral Control",
       "min": 0, "max": 255, "step": 5, "label_format": "blinker_min_speed", "layout": "stacked",
       "visible_if": {"param": "BlinkerPauseLateralControl", "eq": "1"}},
      {"type": "option", "param": "BlinkerLateralReengageDelay", "label": "Post-Blinker Delay",
       "min": 0, "max": 10, "step": 1, "label_format": "blinker_delay", "layout": "stacked",
       "desc": "Delay before lateral control resumes after the turn signal ends.",
       "visible_if": {"param": "BlinkerPauseLateralControl", "eq": "1"}},
      {"type": "separator"},
      {"type": "bool", "param": "EnforceTorqueControl", "label": "Enforce Torque Lateral Control",
       "offroad_only": True, "capability": "torque_allowed",
       "desc": "Enable this to enforce sunnypilot to steer with Torque lateral control."},
      {"type": "subpanel", "target": "steering__torque", "label": "Customize Torque Params", "button": "CUSTOMIZE",
       "requires": {"param": "EnforceTorqueControl", "eq": "1"}},
      {"type": "separator"},
      {"type": "bool", "param": "NeuralNetworkLateralControl", "label": "Neural Network Lateral Control (NNLC)",
       "offroad_only": True, "capability": "torque_allowed"},
    ],
  },
  {
    "id": "cruise",
    "title": "Cruise",
    "widgets": [
      {"type": "bool", "param": "IntelligentCruiseButtonManagement", "label": "Intelligent Cruise Button Management (ICBM) (Alpha)",
       "offroad_only": True, "dynamic_desc": "icbm",
       "desc": "When enabled, sunnypilot will attempt to manage the built-in cruise control buttons by emulating button presses for limited longitudinal control."},
      {"type": "bool", "param": "DynamicExperimentalControl", "label": "Enable Dynamic Experimental Control",
       "desc": "Let the model decide when to use sunnypilot ACC or sunnypilot End to End Longitudinal.",
       "capability": "longitudinal"},
      {"type": "bool", "param": "SmartCruiseControlVision", "label": "Smart Cruise Control - Vision",
       "desc": "Use vision path predictions to estimate the appropriate speed to drive through turns ahead.",
       "capability": "scc"},
      {"type": "bool", "param": "SmartCruiseControlMap", "label": "Smart Cruise Control - Map",
       "desc": "Use map data to estimate the appropriate speed to drive through turns ahead.",
       "capability": "scc"},
      {"type": "bool", "param": "CustomAccIncrementsEnabled", "label": "Custom ACC Speed Increments",
       "offroad_only": True, "dynamic_desc": "custom_acc",
       "desc": "Enable custom Short & Long press increments for cruise speed increase/decrease.",
       "capability": "custom_acc"},
      {"type": "int", "param": "CustomAccShortPressIncrement", "label": "Short Press Increment", "min": 1, "max": 10, "step": 1,
       "visible_if": {"param": "CustomAccIncrementsEnabled", "eq": "1"}, "capability": "custom_acc"},
      {"type": "option", "param": "CustomAccLongPressIncrement", "label": "Long Press Increment",
       "min": 1, "max": 3, "step": 1, "label_format": "acc_long_press",
       "value_map": {"1": 1, "2": 5, "3": 10},
       "visible_if": {"param": "CustomAccIncrementsEnabled", "eq": "1"}, "capability": "custom_acc"},
      {"type": "subpanel", "target": "cruise__sla", "label": "Speed Limit", "button": "CUSTOMIZE"},
      {"type": "subpanel", "target": "cruise__longitudinal_mpc_tuning", "label": "Longitudinal MPC Tuning", "button": "CUSTOMIZE",
       "capability": "longitudinal"},
    ],
  },
  {
    "id": "navigation",
    "title": "Navigation",
    "widgets": [
      {"type": "bool", "param": "AmapEnabled", "label": "Enable Amap Navigation", "offroad_only": True,
       "desc": "Use Amap (Gaode) navigation data for map-based features."},
      {"type": "bool", "param": "CarrotEnabled", "label": "Enable Carrot Navigation", "offroad_only": True,
       "desc": "Use Carrot navigation data for map-based features."},
      {"type": "bool", "param": "CarrotNaviV2Enabled", "label": "Enable Carrot Navi v2 (7714)", "offroad_only": True,
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "desc": "Use the 7714 WebSocket v2 rich navigation stream (traffic, lanes, crossroad images)."},
      {"type": "int", "param": "CarrotManUdpPort", "label": "Carrot UDP Port", "min": 1024, "max": 65535, "step": 1,
       "offroad_only": True,
       "desc": "UDP port the Carrot companion app pushes navigation data to. Must match the port configured in the app (0 disables)."},
      {"type": "bool", "param": "CarrotWebEnabled", "label": "Carrot Web Panel", "offroad_only": True,
       "desc": "Serve the carrot tuning page (/nav_params) and four-corner radar visualisation (/radar) on port 8088."},
      {"type": "readonly", "param": "CarName", "label": "Car Model",
       "desc": "Identified car model, sent automatically with Carrot FTP uploads and shown in the companion app."},
      {"type": "custom", "custom": "amap_api_key", "label": "Amap API Key", "offroad_only": True,
       "desc": "API key for Amap services. Tap EDIT to enter or update the key."},
      {"type": "separator"},
      {"type": "multiple_button", "param": "CarrotPanelSide", "label": "Carrot Nav Panel Side",
       "offroad_only": True,
       "buttons": ["Left", "Right"],
       "desc": "Place the onroad Carrot navigation panel on the left or right side of the screen."},
      {"type": "int", "param": "CarrotPanelOpacity", "label": "Carrot Nav Panel Opacity",
       "min": 10, "max": 100, "step": 5, "offroad_only": True,
       "desc": "Opacity of the onroad Carrot navigation panel, in percent. Default 100."},
      {"type": "custom", "custom": "navigation_provider", "label": "Map Provider",
       "desc": "Current map data source used for speed limits and road names. Amap requires an API key to be set above."},
      {"type": "custom", "custom": "carrot_navi_debug", "label": "Carrot Navi Debug",
       "desc": "View the last navigation event summary handled by CarrotManager."},
      {"type": "separator"},
      {"type": "multiple_button", "param": "MyDrivingMode", "label": "Carrot Driving Mode",
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "buttons": ["Eco", "Normal", "Sport", "Safe"],
       "desc": "Carrot driving style preset."},
      {"type": "multiple_button", "param": "TrafficLightDetectMode", "label": "Traffic Light Assist",
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "buttons": ["Off", "Red Stop", "Red Stop + Green Go"],
       "desc": "Stop at red lights and optionally resume on green when using model-based stop line detection."},
      {"type": "bool", "param": "CarrotCurveSpeedEnabled", "label": "Navigation Curve Speed", "default": True,
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "desc": "Slow down for curves using navigation route curvature."},
      {"type": "bool", "param": "CarrotNavCruiseSpeedEnabled", "label": "Navigation Cruise Speed", "default": True,
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "desc": "Use navigation desired speed to limit cruise set speed."},
      {"type": "bool", "param": "CarrotHudInfoEnabled", "label": "Extended HUD Info", "default": True,
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "desc": "Show blind spot state, side vehicle distance, and traffic light info on the HUD."},
      {"type": "subpanel", "target": "navigation__carrot_tuning", "label": "Carrot Tuning", "button": "CUSTOMIZE"},
    ],
  },
  {
    "id": "visuals",
    "title": "Visuals",
    "widgets": [
      {"type": "bool", "param": "BlindSpot", "label": "Show Blind Spot Warnings",
       "desc": "Enabling this will display warnings when a vehicle is detected in your blind spot as long as your car has BSM supported."},
      {"type": "bool", "param": "TorqueBar", "label": "Steering Arc",
       "desc": "Display steering arc on the driving screen when lateral control is enabled."},
      {"type": "bool", "param": "RainbowMode", "label": "Enable Tesla Rainbow Mode",
       "desc": "A beautiful rainbow effect on the path the model wants to take. It does not affect driving in any way."},
      {"type": "bool", "param": "StandstillTimer", "label": "Enable Standstill Timer",
       "desc": "Show a timer on the HUD when the car is at a standstill."},
      {"type": "bool", "param": "RoadNameToggle", "label": "Display Road Name",
       "desc": "Displays the name of the road the car is traveling on. The OpenStreetMap database of the location must be downloaded from the OSM panel to fetch the road name."},
      {"type": "bool", "param": "GreenLightAlert", "label": "Green Traffic Light Alert (Beta)",
       "desc": "A chime and on-screen alert will play when the traffic light you are waiting for turns green and you have no vehicle in front of you. Note: This chime is only designed as a notification. It is the driver's responsibility to observe their environment and make decisions accordingly."},
      {"type": "bool", "param": "LeadDepartAlert", "label": "Lead Departure Alert (Beta)",
       "desc": "A chime and on-screen alert will play when you are stopped, and the vehicle in front of you start moving. Note: This chime is only designed as a notification. It is the driver's responsibility to observe their environment and make decisions accordingly."},
      {"type": "bool", "param": "TrueVEgoUI", "label": "Speedometer: Always Display True Speed",
       "desc": "For applicable vehicles, always display the true vehicle current speed from wheel speed sensors."},
      {"type": "bool", "param": "HideVEgoUI", "label": "Speedometer: Hide from Onroad Screen",
       "desc": "When enabled, the speedometer on the onroad screen is not displayed."},
      {"type": "bool", "param": "ShowTurnSignals", "label": "Display Turn Signals",
       "desc": "When enabled, visual turn indicators are drawn on the HUD."},
      {"type": "bool", "param": "RocketFuel", "label": "Real-time Acceleration Bar",
       "desc": "Show an indicator on the left side of the screen to display real-time vehicle acceleration and deceleration. This displays what the car is currently doing, not what the planner is requesting."},
      {"type": "multiple_button", "param": "ChevronInfo", "label": "Display Metrics Below Chevron",
       "dynamic_desc": "chevron", "capability": "longitudinal",
       "buttons": ["Off", "Distance", "Speed", "Time", "All"]},
      {"type": "multiple_button", "param": "DevUIInfo", "label": "Developer UI",
       "desc": "Display real-time parameters and metrics from various sources.",
       "buttons": ["Off", "Bottom", "Right", "Right & Bottom"]},
    ],
  },
  {
    "id": "display",
    "title": "Display",
    "widgets": [
      {"type": "option", "param": "Brightness", "label": "Screen Brightness",
       "min": 0, "max": 100, "step": 5, "label_format": "offroad_brightness", "layout": "inline",
       "desc": "Screen brightness when offroad (not driving). 0 uses the device default (50%)."},
      {"type": "option", "param": "OnroadScreenOffBrightness", "label": "Onroad Brightness",
       "min": 0, "max": 22, "step": 1, "label_format": "onroad_brightness", "layout": "inline"},
      {"type": "option", "param": "OnroadScreenOffTimer", "label": "Onroad Brightness Delay",
       "min": 0, "max": 9, "step": 1, "label_format": "onroad_brightness_timer",
       "value_map": {"0": 0, "1": 3, "2": 5, "3": 10, "4": 15, "5": 30,
                     "6": 60, "7": 180, "8": 300, "9": 600},
       "layout": "inline"},
      {"type": "option", "param": "InteractivityTimeout", "label": "Interactivity Timeout",
       "min": 0, "max": 120, "step": 10, "label_format": "interactivity_timeout",
       "desc": "Apply a custom timeout for settings UI. This is the time after which settings UI closes automatically if user is not interacting with the screen.",
       "layout": "inline"},
      {"type": "bool", "param": "HideFirehosePrompt", "label": "Hide Firehose Prompt",
       "desc": "Hide the Firehose prompt on the home screen. The prompt will not be rendered when this is enabled."},
      {"type": "bool", "param": "ScreenSaverEnabled", "label": "Screen Saver",
       "desc": "Show a screen saver when the device is offroad and idle, instead of turning the screen off."},
      {"type": "option", "param": "ScreenSaverTimeout", "label": "Screen Saver Duration",
       "min": 60, "max": 600, "step": 60, "label_format": "screensaver_timeout",
       "desc": "How long the screen saver runs before the screen turns off.",
       "visible_if": {"param": "ScreenSaverEnabled", "eq": "1"}},
      {"type": "separator"},
      {"type": "custom", "custom": "stream_headless_mode", "desc_i18n": "webui_headless_mode_desc"},
      {"type": "custom", "custom": "stream_preview_quality", "desc_i18n": "webui_preview_quality_desc"},
      {"type": "custom", "custom": "stream_webcodecs"},
      {"type": "custom", "custom": "stream_diagnostics"},
    ],
  },
  {
    "id": "storage",
    "title": "Storage",
    "custom": "storage",
    "widgets": [],
  },
  {
    "id": "osm",
    "title": "OSM",
    "custom": "osm",
    "widgets": [],
  },
  {
    "id": "trips",
    "title": "Trips",
    "custom": "trips",
    "widgets": [],
  },
  {
    "id": "vehicle",
    "title": "Vehicle",
    "custom": "vehicle",
    "widgets": [],
  },
  {
    "id": "firehose",
    "title": "Data",
    "custom": "firehose",
    "widgets": [],
  },
  {
    "id": "developer",
    "title": "Developer",
    "widgets": [
      {"type": "bool", "param": "AdbEnabled", "label": "Enable ADB", "offroad_only": True,
       "desc": "ADB (Android Debug Bridge) allows connecting to your device over USB or over the network. See https://docs.comma.ai/how-to/connect-to-comma for more info."},
      {"type": "bool", "param": "SshEnabled", "label": "Enable SSH"},
      {"type": "custom", "custom": "ssh_keys", "label": "SSH Keys"},
      {"type": "bool", "param": "JoystickDebugMode", "label": "Joystick Debug Mode",
       "offroad_only": True, "capability": "not_release"},
      {"type": "bool", "param": "LongitudinalManeuverMode", "label": "Longitudinal Maneuver Mode",
       "offroad_only": True, "capability": "longitudinal_not_release"},
      {"type": "bool", "param": "LateralManeuverMode", "label": "Lateral Maneuver Mode",
       "offroad_only": True, "capability": "not_release"},
      {"type": "bool", "param": "AlphaLongitudinalEnabled", "label": "sunnypilot Longitudinal Control (Alpha)",
       "needs_cycle": True, "offroad_only": True, "capability": "alpha_longitudinal",
       "desc": "WARNING: sunnypilot longitudinal control is in alpha for this car and may disable Automatic Emergency Braking (AEB). On this car, sunnypilot defaults to the car's built-in ACC instead of sunnypilot's longitudinal control. Enable this to switch to sunnypilot longitudinal control. Enabling Experimental mode is recommended when enabling sunnypilot longitudinal control alpha. Changing this setting will restart sunnypilot if the car is powered on."},
      {"type": "bool", "param": "ShowDebugInfo", "label": "UI Debug Mode", "capability": "not_release"},
      {"type": "bool", "param": "ShowAdvancedControls", "label": "Show Advanced Controls",
       "desc": "Toggle visibility of advanced sunnypilot controls. This only changes the visibility of the toggles; it does not change the actual enabled/disabled state."},
      {"type": "bool", "param": "EnableGithubRunner", "label": "GitHub Runner Service",
       "desc": "Enables or disables the GitHub runner service.",
       "visible_if": {"param": "ShowAdvancedControls", "eq": "1"}, "capability": "not_release"},
      {"type": "bool", "param": "EnableCopyparty", "label": "copyparty Service",
       "desc": "copyparty is a very capable file server, you can use it to download your routes, view your logs and even make some edits on some files from your browser. Requires you to connect to your comma locally via its IP address.",
       "visible_if": {"param": "ShowAdvancedControls", "eq": "1"}},
      {"type": "bool", "param": "QuickBootToggle", "label": "Quickboot Mode",
       "visible_if": {"param": "ShowAdvancedControls", "eq": "1"}, "capability": "not_release_or_tested"},
      {"type": "action", "action": "developer_error_log", "label": "Error Log", "button": "VIEW",
       "capability": "not_release"},
    ],
  },
]

SUBPANELS: dict[str, dict[str, Any]] = {
  "navigation__carrot_tuning": {
    "id": "navigation__carrot_tuning",
    "title": "Carrot Tuning",
    "parent": "navigation",
    "widgets": [
      {"type": "section", "label": "ATC / Fork"},
      {"type": "int", "param": "AutoTurnDistOffset", "label": "ATC Turn Distance Offset", "min": 0, "max": 1000, "step": 5,
       "desc": "Extra distance subtracted from the ATC turn trigger distance. Default 0."},
      {"type": "int", "param": "AutoForkDistOffset", "label": "Fork Distance Offset", "min": 0, "max": 500, "step": 5,
       "desc": "Distance before a fork at which speed control starts. Default 30."},
      {"type": "int", "param": "AutoForkDistOffsetH", "label": "Fork Distance Offset (Highway)", "min": 0, "max": 2000, "step": 10,
       "desc": "Highway variant of the fork distance offset. Default 1000."},
      {"type": "int", "param": "AutoDoForkBlinkerDist", "label": "Fork Blinker Distance", "min": 0, "max": 200, "step": 1,
       "desc": "Distance before a fork at which the blinker is auto-activated. Default 15."},
      {"type": "int", "param": "AutoDoForkBlinkerDistH", "label": "Fork Blinker Distance (Highway)", "min": 0, "max": 500, "step": 1,
       "desc": "Highway variant. Default 30."},
      {"type": "int", "param": "AutoDoForkNavDist", "label": "Fork Nav Distance", "min": 0, "max": 200, "step": 1,
       "desc": "Distance before a fork at which nav-based turn control engages. Default 15."},
      {"type": "int", "param": "AutoDoForkNavDistH", "label": "Fork Nav Distance (Highway)", "min": 0, "max": 500, "step": 1,
       "desc": "Highway variant. Default 50."},
      {"type": "int", "param": "AutoDoForkDecalDist", "label": "Fork Decel Distance", "min": 0, "max": 300, "step": 1,
       "desc": "Distance before a fork at which deceleration starts. Default 20."},
      {"type": "int", "param": "AutoDoForkDecalDistH", "label": "Fork Decel Distance (Highway)", "min": 0, "max": 500, "step": 1,
       "desc": "Highway variant. Default 50."},
      {"type": "int", "param": "AutoForkDecalRate", "label": "Fork Decel Rate", "min": 0, "max": 500, "step": 10,
       "desc": "Deceleration rate used for fork slowdowns (x0.01 m/s^2). Default 80."},
      {"type": "int", "param": "AutoForkDecalRateH", "label": "Fork Decel Rate (Highway)", "min": 0, "max": 500, "step": 10,
       "desc": "Highway variant. Default 80."},
      {"type": "int", "param": "AutoForkSpeedMin", "label": "Fork Speed Min", "min": 0, "max": 120, "step": 5,
       "desc": "Minimum speed target when slowing for a fork (km/h). Default 45."},
      {"type": "int", "param": "AutoForkSpeedMinH", "label": "Fork Speed Min (Highway)", "min": 0, "max": 120, "step": 5,
       "desc": "Highway variant. Default 60."},
      {"type": "int", "param": "AutoKeepForkSpeed", "label": "Keep Fork Speed", "min": 0, "max": 60, "step": 1,
       "desc": "Speed window in which the fork speed is kept instead of re-targeting. Default 5."},
      {"type": "int", "param": "AutoKeepForkSpeedH", "label": "Keep Fork Speed (Highway)", "min": 0, "max": 60, "step": 1,
       "desc": "Highway variant. Default 5."},
      {"type": "int", "param": "AutoUpRoadLimit", "label": "Road Limit Raise Threshold", "min": 0, "max": 120, "step": 5,
       "desc": "vEgo threshold (km/h) for raising road-type limits. Default 0 (disabled)."},
      {"type": "int", "param": "AutoUpRoadLimit40KMH", "label": "Road Limit Raise Margin", "min": 0, "max": 60, "step": 1,
       "desc": "Margin applied when raising limits below 40 km/h. Default 15."},
      {"type": "int", "param": "AutoUpHighwayRoadLimit", "label": "Highway Limit Raise Threshold", "min": 0, "max": 160, "step": 5,
       "desc": "vEgo threshold (km/h) for raising highway road-type limits. Default 0 (disabled)."},
      {"type": "int", "param": "AutoUpHighwayRoadLimit40KMH", "label": "Highway Limit Raise Margin", "min": 0, "max": 60, "step": 1,
       "desc": "Margin applied when raising highway limits below 40 km/h. Default 15."},
      {"type": "bool", "param": "AutoTurnInNotRoadEdge", "label": "Auto Turn Off Road Edge", "default": True,
       "desc": "Allow auto turns when the lane is not at a road edge. Default on."},
      {"type": "separator"},
      {"type": "section", "label": "Curve Speed"},
      {"type": "int", "param": "AutoCurveSpeedFactorH", "label": "Curve Speed Factor (Highway)", "min": 10, "max": 200, "step": 5,
       "desc": "Percent multiplier on highway curve speed targets. Default 100."},
      {"type": "int", "param": "AutoCurveSpeedAggressivenessH", "label": "Curve Speed Aggressiveness (Highway)", "min": 10, "max": 200, "step": 5,
       "desc": "Percent tuning of highway curve deceleration aggressiveness. Default 100."},
      {"type": "separator"},
      {"type": "section", "label": "Blind Spot (BSD)"},
      {"type": "bool", "param": "DisableBlindSpot", "label": "Disable Blind Spot", "default": False,
       "desc": "Disable the Carrot blind-spot detection/lane-change blocking. Default off."},
      {"type": "int", "param": "DynamicBlindRange", "label": "Dynamic Blind Range", "min": 0, "max": 100, "step": 5,
       "desc": "Enable dynamic blind-spot range based on speed. Default 0 (disabled)."},
      {"type": "int", "param": "DynamicBlindDistance", "label": "Dynamic Blind Distance", "min": 0, "max": 100, "step": 5,
       "desc": "Base dynamic blind-spot distance. Default 0."},
      {"type": "int", "param": "BsdDelayTime", "label": "BSD Delay Time", "min": 0, "max": 100, "step": 5,
       "desc": "Blind-spot detection hold time (x0.1 s). Default 20 (2.0 s)."},
      {"type": "int", "param": "SideBsdDelayTime", "label": "Side BSD Delay Time", "min": 0, "max": 100, "step": 5,
       "desc": "Side blind-spot detection hold time (x0.1 s). Default 20 (2.0 s)."},
      {"type": "int", "param": "SideRelDistTime", "label": "Side Rel Dist Time", "min": 0, "max": 100, "step": 5,
       "desc": "Time constant for side relative-distance filtering (x0.1 s). Default 10 (1.0 s)."},
      {"type": "int", "param": "SidevRelDistTime", "label": "Side vRel Dist Time", "min": 0, "max": 100, "step": 5,
       "desc": "Time constant for side relative-speed filtering (x0.1 s). Default 10 (1.0 s)."},
      {"type": "int", "param": "SideRadarMinDist", "label": "Side Radar Min Dist", "min": 0, "max": 50, "step": 1,
       "desc": "Minimum side radar distance considered valid. Default 0."},
      {"type": "separator"},
      {"type": "section", "label": "Lane Change / Blinker"},
      {"type": "bool", "param": "StockBlinkerCtrl", "label": "Stock Blinker Control", "default": False,
       "desc": "Let the stock system control blinkers during auto turns. Default off."},
      {"type": "bool", "param": "ExtBlinkerCtrlTest", "label": "External Blinker Control Test", "default": False,
       "desc": "Test mode for external blinker control. Default off."},
      {"type": "int", "param": "BlinkerMode", "label": "Blinker Mode", "min": 0, "max": 2, "step": 1,
       "desc": "Blinker control mode. Default 1."},
      {"type": "int", "param": "LaneStabTime", "label": "Lane Stabilize Time", "min": 0, "max": 200, "step": 10,
       "desc": "Time a lane must stay stable before auto turn uses it (x0.1 s). Default 50 (5.0 s)."},
      {"type": "bool", "param": "ContinuousLaneChange", "label": "Continuous Lane Change", "default": True,
       "desc": "Allow multiple consecutive auto lane changes. Default on."},
      {"type": "int", "param": "ContinuousLaneChangeCnt", "label": "Continuous Lane Change Count", "min": 1, "max": 10, "step": 1,
       "desc": "Max consecutive auto lane changes. Default 4."},
      {"type": "int", "param": "ContinuousLaneChangeInterval", "label": "Continuous Lane Change Interval", "min": 0, "max": 30, "step": 1,
       "desc": "Minimum seconds between consecutive auto lane changes. Default 2."},
      {"type": "bool", "param": "AutoTurnLeft", "label": "Auto Turn Left", "default": True,
       "desc": "Enable auto turns to the left. Default on."},
      {"type": "int", "param": "AutoEnTurnNewLaneTime", "label": "New Lane Turn Enable Time", "min": 0, "max": 60, "step": 5,
       "desc": "Seconds a new lane must exist before auto turn engages. Default 0 (disabled)."},
      {"type": "int", "param": "AutoEnTurnNewLaneTimeH", "label": "New Lane Turn Enable Time (Highway)", "min": 0, "max": 60, "step": 5,
       "desc": "Highway variant. Default 0 (disabled)."},
      {"type": "int", "param": "NewLaneWidthDiff", "label": "New Lane Width Diff", "min": 0, "max": 50, "step": 1,
       "desc": "Width difference threshold for detecting a new lane. Default 8."},
      {"type": "separator"},
      {"type": "section", "label": "Vehicle / CAN Speed Arbitration"},
      {"type": "multiple_button", "param": "VehicleNaviCanControl", "label": "Vehicle Navi CAN Control",
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "buttons": ["Off", "Camera/Bump Always", "Camera Always/Bump Route", "Camera/Bump Route"],
       "desc": "How vehicle CAN navigation deceleration is applied. Off disables; mode 1 always applies camera and bump; mode 2 always applies camera and only route bumps; mode 3 applies both only when on route."},
      {"type": "bool", "param": "VehicleNaviSchoolZoneControl", "label": "Vehicle School Zone 30 km/h Limit", "default": False,
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "desc": "Cap target speed at 30 km/h while the vehicle reports a confirmed 30 km/h zone entry."},
      {"type": "multiple_button", "param": "VehicleSpeedCameraControlMode", "label": "Vehicle Speed Camera Mode",
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "buttons": ["Off", "Always Apply", "Gas Floor", "Gas Pause"],
       "desc": "How vehicle CAN speed-camera enforcement is used. Off disables; Always Apply ignores gas; Gas Floor keeps the highest speed reached during override as a floor; Gas Pause pauses deceleration while gas is pressed."},
      {"type": "int", "param": "VehicleSpeedCameraDistanceTime", "label": "Speed Camera Virtual Distance Time", "min": 10, "max": 200, "step": 1,
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "desc": "Virtual deceleration distance time when the vehicle sends only a speed limit without distance. Stored in 0.1 s units (60 = 6.0 s)."},
      {"type": "int", "param": "AutoNaviSpeedBumpEndDistance", "label": "Speed Bump Early Release Distance", "min": 0, "max": 5000, "step": 10,
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "desc": "Release speed-bump deceleration when remaining distance is at or below this value (cm). 0 keeps control until the received point."},
      {"type": "separator"},
      {"type": "section", "label": "Carrot Planner / Cruise"},
      {"type": "text", "param": "TFollowGap1", "label": "Follow Gap 1",
       "desc": "Following distance multiplier for the most aggressive mode. Default 1.8."},
      {"type": "text", "param": "TFollowGap2", "label": "Follow Gap 2",
       "desc": "Following distance multiplier for the sport mode. Default 1.5."},
      {"type": "text", "param": "TFollowGap3", "label": "Follow Gap 3",
       "desc": "Following distance multiplier for the normal mode. Default 1.2."},
      {"type": "text", "param": "TFollowGap4", "label": "Follow Gap 4",
       "desc": "Following distance multiplier for the eco/safe mode. Default 1.0."},
      {"type": "text", "param": "CruiseMaxVals0", "label": "Max Accel 0",
       "desc": "Maximum acceleration at low speed (m/s^2). Default 1.5."},
      {"type": "text", "param": "CruiseMaxVals1", "label": "Max Accel 1",
       "desc": "Maximum acceleration at moderate speed (m/s^2). Default 1.8."},
      {"type": "text", "param": "CruiseMaxVals2", "label": "Max Accel 2",
       "desc": "Maximum acceleration at higher speed (m/s^2). Default 2.0."},
      {"type": "text", "param": "CruiseMaxVals3", "label": "Max Accel 3",
       "desc": "Maximum acceleration at highway speed (m/s^2). Default 2.2."},
      {"type": "text", "param": "CruiseMaxVals4", "label": "Max Accel 4",
       "desc": "Maximum acceleration at high speed (m/s^2). Default 2.4."},
      {"type": "text", "param": "CruiseMaxVals5", "label": "Max Accel 5",
       "desc": "Maximum acceleration at very high speed (m/s^2). Default 2.6."},
      {"type": "text", "param": "CruiseMaxVals6", "label": "Max Accel 6",
       "desc": "Maximum acceleration at top speed (m/s^2). Default 2.8."},
      {"type": "separator"},
      {"type": "section", "label": "Cluster / HUD Map"},
      {"type": "int", "param": "LatSuspendAngleDeg", "label": "Auto Steering Suspend Angle", "min": 45, "max": 300, "step": 10,
       "desc": "Steering angle at which automatic steering is suspended. It resumes when the angle returns within 15 deg. Default 300."},
      {"type": "multiple_button", "param": "ClusterNaviMapTheme", "label": "Cluster Map Theme",
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "buttons": ["Auto", "Dark", "Light"],
       "desc": "Theme used for the cluster navigation map. Changing it reconnects the external navi app."},
      {"type": "multiple_button", "param": "ClusterNaviMapType", "label": "Cluster Map Type",
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "buttons": ["Normal", "Satellite"],
       "desc": "Map style used for the cluster navigation map. Changing it reconnects the external navi app."},
      {"type": "multiple_button", "param": "ClusterNaviMapFps", "label": "Cluster Map FPS",
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "buttons": ["5 FPS", "10 FPS", "20 FPS", "30 FPS"],
       "desc": "Render frame rate for the cluster navigation map. Bitrate is selected automatically."},
      {"type": "bool", "param": "CarrotNaviHudMapProfile", "label": "HUD Map Profile", "default": False,
       "visible_if": {"param": "CarrotEnabled", "eq": "1"},
       "desc": "Use the HUD-optimized map profile (raised screen center) when a HUD map client is connected."},
      {"type": "separator"},
      {"type": "section", "label": "Navi Speed / Sound"},
      {"type": "int", "param": "StopDistanceCarrot", "label": "Stop Distance", "min": 0, "max": 2000, "step": 10,
       "desc": "Distance before a destination stop at which the car slows down. Default 550."},
      {"type": "int", "param": "AutoNaviSpeedCtrlMode", "label": "Navi Speed Control Mode", "min": 0, "max": 2, "step": 1,
       "desc": "Navi speed control strategy. Default 0."},
      {"type": "int", "param": "AutoNaviSpeedDecelRate", "label": "Navi Speed Decel Rate", "min": 0, "max": 500, "step": 10,
       "desc": "Deceleration rate for navi speed control (x0.01 m/s^2). Default 150."},
      {"type": "int", "param": "AutoNaviSpeedSafetyFactor", "label": "Navi Speed Safety Factor", "min": 50, "max": 150, "step": 5,
       "desc": "Percent safety factor applied to navi speed targets. Default 100."},
      {"type": "int", "param": "SoundVolumeAdjust", "label": "Sound Volume Adjust", "min": 0, "max": 200, "step": 10,
       "desc": "Percent adjustment of Carrot sound volume. Default 100."},
      {"type": "int", "param": "SoundVolumeAdjustEngage", "label": "Engage Volume Adjust", "min": 0, "max": 200, "step": 10,
       "desc": "Percent adjustment of the engage sound volume. Default 100."},
      {"type": "bool", "param": "SameSpiCamFilter", "label": "Same Camera Filter", "default": True,
       "desc": "Filter out speed-camera events already passed. Default on."},
      {"type": "bool", "param": "ShowDebugLog", "label": "Show Debug Log", "default": False,
       "desc": "Enable verbose Carrot debug logging. Default off."},
      {"type": "separator"},
      {"type": "separator"},
      {"type": "section", "label": "Longitudinal / Following"},
      {"type": "text", "param": "DynamicTFollow", "label": "Dynamic T-Follow",
       "desc": "Dynamic time-to-follow multiplier applied to the gap. Default 0.0 (disabled)."},
      {"type": "text", "param": "DynamicTFollowLC", "label": "Dynamic T-Follow (Lane Change)",
       "desc": "Dynamic time-to-follow multiplier used during lane changes. Default 100.0."},
      {"type": "int", "param": "LeadAccelResponse", "label": "Lead Accel Response", "min": -100, "max": 100, "step": 5,
       "desc": "Gain on lead vehicle acceleration response for following. Default 0."},
      {"type": "int", "param": "LongActuatorDelay", "label": "Long Actuator Delay", "min": 0, "max": 200, "step": 5,
       "desc": "Longitudinal actuator delay (ms). Default 20."},
      {"type": "int", "param": "LongTuningKf", "label": "Long Tuning Kf", "min": 0, "max": 300, "step": 5,
       "desc": "Longitudinal controller feed-forward gain. Default 100."},
      {"type": "int", "param": "LongTuningKiV", "label": "Long Tuning KiV", "min": 0, "max": 300, "step": 5,
       "desc": "Longitudinal controller integral gain on speed error. Default 0."},
      {"type": "int", "param": "LongTuningKpV", "label": "Long Tuning KpV", "min": 0, "max": 300, "step": 5,
       "desc": "Longitudinal controller proportional gain on speed error. Default 100."},
      {"type": "int", "param": "StoppingAccel", "label": "Stopping Accel", "min": -200, "max": 0, "step": 5,
       "desc": "Acceleration used while coming to a stop (%). Default -50."},
      {"type": "int", "param": "TFollowDecelBoost", "label": "T-Follow Decel Boost", "min": 0, "max": 200, "step": 5,
       "desc": "Extra deceleration boost added to the time-to-follow gap. Default 0."},
      {"type": "separator"},
      {"type": "section", "label": "Cruise / Acceleration"},
      {"type": "int", "param": "AutoCruiseControl", "label": "Auto Cruise Control", "min": 0, "max": 3, "step": 1,
       "desc": "Automatic cruise-control behavior mode. Default 0."},
      {"type": "int", "param": "CarrotCruiseAtcDecel", "label": "Cruise ATC Decel", "min": -100, "max": 0, "step": 1,
       "desc": "Cruise decel for auto-turn-control (%). Default -1 (auto)."},
      {"type": "int", "param": "CarrotCruiseDecel", "label": "Cruise Decel", "min": -100, "max": 0, "step": 1,
       "desc": "Cruise deceleration limit (%). Default -1 (auto)."},
      {"type": "int", "param": "CruiseButtonLongDelay", "label": "Cruise Button Long Delay", "min": 0, "max": 200, "step": 5,
       "desc": "Long-press delay for cruise buttons (x0.1 s). Default 40 (4.0 s)."},
      {"type": "int", "param": "CruiseButtonMode", "label": "Cruise Button Mode", "min": 0, "max": 3, "step": 1,
       "desc": "Cruise button handling mode. Default 0."},
      {"type": "int", "param": "CruiseEcoControl", "label": "Cruise Eco Control", "min": 0, "max": 3, "step": 1,
       "desc": "Eco cruise control mode. Default 2."},
      {"type": "int", "param": "CruiseOnDist", "label": "Cruise Engage Distance", "min": 0, "max": 300, "step": 5,
       "desc": "Distance at which cruise auto-engages (m). Default 0."},
      {"type": "int", "param": "CruiseSpeed1", "label": "Cruise Speed Preset 1", "min": 0, "max": 100, "step": 1,
       "desc": "Cruise speed preset 1 (km/h). Default 10."},
      {"type": "int", "param": "CruiseSpeed2", "label": "Cruise Speed Preset 2", "min": 0, "max": 100, "step": 1,
       "desc": "Cruise speed preset 2 (km/h). Default 10."},
      {"type": "int", "param": "CruiseSpeed3", "label": "Cruise Speed Preset 3", "min": 0, "max": 100, "step": 1,
       "desc": "Cruise speed preset 3 (km/h). Default 10."},
      {"type": "int", "param": "CruiseSpeed4", "label": "Cruise Speed Preset 4", "min": 0, "max": 100, "step": 1,
       "desc": "Cruise speed preset 4 (km/h). Default 10."},
      {"type": "int", "param": "CruiseSpeed5", "label": "Cruise Speed Preset 5", "min": 0, "max": 100, "step": 1,
       "desc": "Cruise speed preset 5 (km/h). Default 10."},
      {"type": "int", "param": "CruiseSpeedUnit", "label": "Cruise Speed Unit", "min": 0, "max": 100, "step": 1,
       "desc": "Cruise speed unit scaling. Default 10."},
      {"type": "int", "param": "CruiseSpeedUnitBasic", "label": "Cruise Speed Unit (Basic)", "min": 0, "max": 100, "step": 1,
       "desc": "Cruise speed unit scaling for basic mode. Default 10."},
      {"type": "separator"},
      {"type": "section", "label": "Speed Limits / Road Speed"},
      {"type": "int", "param": "AutoRoadSpeedAdjust", "label": "Auto Road Speed Adjust", "min": -50, "max": 50, "step": 1,
       "desc": "Automatic adjustment to road speed limit (km/h). Default 0."},
      {"type": "int", "param": "AutoSpeedUptoRoadSpeedLimit", "label": "Auto Speed Up To Limit", "min": 0, "max": 2, "step": 1,
       "desc": "Automatically raise target speed up to the road speed limit. Default 0 (off)."},
      {"type": "int", "param": "SpeedFromPCM", "label": "Speed From PCM", "min": 0, "max": 2, "step": 1,
       "desc": "Use vehicle PCM-reported speed source mode. Default 0."},
      {"type": "int", "param": "RoadType", "label": "Road Type Override", "min": -1, "max": 5, "step": 1,
       "desc": "Road type override used by ATC speed logic (-1 = auto). Default -1."},
      {"type": "separator"},
      {"type": "section", "label": "Traffic Stop / Lights"},
      {"type": "int", "param": "HapticFeedbackWhenSpeedCamera", "label": "Haptic On Speed Camera", "min": 0, "max": 2, "step": 1,
       "desc": "Haptic feedback when a speed camera is detected. Default 0."},
      {"type": "int", "param": "TrafficStopDistanceAdjust", "label": "Traffic Stop Distance Adjust", "min": -500, "max": 500, "step": 10,
       "desc": "Adjust the traffic-light stop distance (cm). Default -150."},
      {"type": "separator"},
      {"type": "section", "label": "Lane Change / Lane Line / ONNX BSD"},
      {"type": "int", "param": "LaneChangeBsd", "label": "Lane Change BSD", "min": 0, "max": 2, "step": 1,
       "desc": "Blind-spot requirement mode for auto lane change. Default 0."},
      {"type": "int", "param": "LaneChangeDelay", "label": "Lane Change Delay", "min": 0, "max": 100, "step": 1,
       "desc": "Delay before auto lane change engages (x0.1 s). Default 0."},
      {"type": "int", "param": "LaneChangeNeedTorque", "label": "Lane Change Need Torque", "min": 0, "max": 2, "step": 1,
       "desc": "Require steering torque before lane change. Default 0."},
      {"type": "int", "param": "LaneLineCheck", "label": "Lane Line Check", "min": 0, "max": 2, "step": 1,
       "desc": "Lane-line based safety check mode. Default 0."},
      {"type": "int", "param": "OnnxBsdIntervalMs", "label": "ONNX BSD Interval", "min": 50, "max": 1000, "step": 10,
       "desc": "ONNX blind-spot model inference interval (ms). Default 250."},
      {"type": "int", "param": "OnnxBsdSmoothingMs", "label": "ONNX BSD Smoothing", "min": 0, "max": 1000, "step": 10,
       "desc": "ONNX blind-spot detection smoothing window (ms). Default 200."},
      {"type": "int", "param": "OnnxBsdThreshold", "label": "ONNX BSD Threshold", "min": 0, "max": 100, "step": 1,
       "desc": "ONNX blind-spot confidence threshold (%). Default 45."},
      {"type": "int", "param": "UseLaneLineCurveSpeed", "label": "Use Lane Line Curve Speed", "min": 0, "max": 2, "step": 1,
       "desc": "Use lane-line curvature for curve speed. Default 0."},
      {"type": "int", "param": "UseLaneLineSpeed", "label": "Use Lane Line Speed", "min": 0, "max": 2, "step": 1,
       "desc": "Use lane-line based speed. Default 0."},
      {"type": "separator"},
      {"type": "section", "label": "Steering / Lateral"},
      {"type": "int", "param": "AlwaysLateral", "label": "Always Lateral", "min": 0, "max": 2, "step": 1,
       "desc": "Keep lateral control always engaged mode. Default 0."},
      {"type": "int", "param": "CustomSR", "label": "Custom Steer Ratio", "min": 0, "max": 100, "step": 1,
       "desc": "Custom steering ratio override (%). Default 0."},
      {"type": "int", "param": "CustomSteerDeltaDown", "label": "Custom Steer Delta Down", "min": 0, "max": 100, "step": 1,
       "desc": "Custom steer rate limit down. Default 0."},
      {"type": "int", "param": "CustomSteerDeltaDownLC", "label": "Custom Steer Delta Down (LC)", "min": 0, "max": 100, "step": 1,
       "desc": "Custom steer rate limit down during lane change. Default 0."},
      {"type": "int", "param": "CustomSteerDeltaUp", "label": "Custom Steer Delta Up", "min": 0, "max": 100, "step": 1,
       "desc": "Custom steer rate limit up. Default 0."},
      {"type": "int", "param": "CustomSteerDeltaUpLC", "label": "Custom Steer Delta Up (LC)", "min": 0, "max": 100, "step": 1,
       "desc": "Custom steer rate limit up during lane change. Default 0."},
      {"type": "int", "param": "CustomSteerMax", "label": "Custom Steer Max", "min": 0, "max": 100, "step": 1,
       "desc": "Custom maximum steering value. Default 0."},
      {"type": "int", "param": "LatMpcAccelCost", "label": "Lat MPC Accel Cost", "min": 0, "max": 500, "step": 5,
       "desc": "Lateral MPC acceleration cost. Default 100."},
      {"type": "int", "param": "LatMpcJerkCost", "label": "Lat MPC Jerk Cost", "min": 0, "max": 100, "step": 1,
       "desc": "Lateral MPC jerk cost. Default 1."},
      {"type": "int", "param": "LatMpcMotionCost", "label": "Lat MPC Motion Cost", "min": 0, "max": 100, "step": 1,
       "desc": "Lateral MPC motion cost. Default 7."},
      {"type": "int", "param": "LatMpcPathCost", "label": "Lat MPC Path Cost", "min": 0, "max": 1000, "step": 5,
       "desc": "Lateral MPC path-following cost. Default 200."},
      {"type": "int", "param": "LatMpcSteeringRateCost", "label": "Lat MPC Steering Rate Cost", "min": 0, "max": 100, "step": 1,
       "desc": "Lateral MPC steering-rate cost. Default 7."},
      {"type": "int", "param": "LateralTorqueCustom", "label": "Lateral Torque Custom", "min": 0, "max": 2, "step": 1,
       "desc": "Use custom lateral torque tuning. Default 1."},
      {"type": "int", "param": "LateralTorqueFriction", "label": "Lateral Torque Friction", "min": 0, "max": 300, "step": 5,
       "desc": "Lateral torque friction estimate. Default 100."},
      {"type": "int", "param": "LateralTorqueKd", "label": "Lateral Torque Kd", "min": 0, "max": 300, "step": 5,
       "desc": "Lateral torque derivative gain. Default 0."},
      {"type": "int", "param": "LateralTorqueKf", "label": "Lateral Torque Kf", "min": 0, "max": 300, "step": 5,
       "desc": "Lateral torque feed-forward gain. Default 100."},
      {"type": "int", "param": "LateralTorqueKiV", "label": "Lateral Torque KiV", "min": 0, "max": 300, "step": 5,
       "desc": "Lateral torque integral gain on speed error. Default 10."},
      {"type": "int", "param": "LateralTorqueKpV", "label": "Lateral Torque KpV", "min": 0, "max": 300, "step": 5,
       "desc": "Lateral torque proportional gain on speed error. Default 100."},
      {"type": "int", "param": "PathOffset", "label": "Path Offset", "min": -100, "max": 100, "step": 1,
       "desc": "Lateral path offset (cm). Default 0."},
      {"type": "int", "param": "SteerActuatorDelay", "label": "Steer Actuator Delay", "min": 0, "max": 200, "step": 5,
       "desc": "Steering actuator delay (ms). Default 30."},
      {"type": "int", "param": "SteerRatioRate", "label": "Steer Ratio Rate", "min": 0, "max": 300, "step": 5,
       "desc": "Steering ratio adaptation rate. Default 100."},
      {"type": "separator"},
      {"type": "section", "label": "Vehicle / CAN / Buttons"},
      {"type": "int", "param": "AutoGasCancelSpeed", "label": "Auto Gas Cancel Speed", "min": 0, "max": 200, "step": 5,
       "desc": "Speed above which auto-gas cancels (km/h). Default 30."},
      {"type": "int", "param": "AutoGasSyncSpeed", "label": "Auto Gas Sync Speed", "min": 0, "max": 200, "step": 5,
       "desc": "Auto-gas sync speed (km/h). Default 0."},
      {"type": "int", "param": "AutoGasTokSpeed", "label": "Auto Gas Tok Speed", "min": 0, "max": 200, "step": 5,
       "desc": "Auto-gas token speed (km/h). Default 0."},
      {"type": "int", "param": "CancelButtonMode", "label": "Cancel Button Mode", "min": 0, "max": 3, "step": 1,
       "desc": "Behavior of the cancel button. Default 0."},
      {"type": "int", "param": "LfaButtonMode", "label": "LFA Button Mode", "min": 0, "max": 3, "step": 1,
       "desc": "LFA button handling mode. Default 0."},
      {"type": "int", "param": "PaddleMode", "label": "Paddle Mode", "min": 0, "max": 3, "step": 1,
       "desc": "Steering-wheel paddle mode. Default 1."},
      {"type": "separator"},
      {"type": "section", "label": "Misc Driving"},
      {"type": "int", "param": "ApplyModelSpeed", "label": "Apply Model Speed", "min": 0, "max": 2, "step": 1,
       "desc": "Apply model-predicted speed mode. Default 0."},
      {"type": "int", "param": "AutoEngage", "label": "Auto Engage", "min": 0, "max": 2, "step": 1,
       "desc": "Automatic engagement mode. Default 0."},
      {"type": "int", "param": "MyDrivingModeAuto", "label": "My Driving Mode Auto", "min": 0, "max": 2, "step": 1,
       "desc": "Automatically switch driving mode. Default 0."},
      {"type": "int", "param": "SoftHoldOnCancel", "label": "Soft Hold On Cancel", "min": 0, "max": 2, "step": 1,
       "desc": "Soft hold behavior when cancelling. Default 0."},
      {"type": "int", "param": "VEgoStopping", "label": "vEgo Stopping", "min": 0, "max": 500, "step": 5,
       "desc": "Vehicle speed threshold treated as stopped (x0.01 m/s). Default 50 (0.5 m/s)."},
      {"type": "separator"},
      {"type": "separator"},
      {"type": "separator"},
      {"type": "section", "label": "ATC / Turn Control"},
      {"type": "int", "param": "AutoTurnControl", "label": "Auto Turn Control", "min": 0, "max": 3, "step": 1, "desc": "Automatic turn control mode. Default 0."},
      {"type": "int", "param": "AutoTurnControlSpeedTurn", "label": "ATC Turn Speed", "min": 0, "max": 100, "step": 1, "desc": "Speed (km/h) below which auto turn control engages. Default 20."},
      {"type": "int", "param": "AutoTurnControlTurnEnd", "label": "ATC Turn End Speed", "min": 0, "max": 50, "step": 1, "desc": "Speed (km/h) at which an auto turn is considered complete. Default 6."},
      {"type": "int", "param": "AutoTurnMapChange", "label": "ATC Map Change", "min": 0, "max": 2, "step": 1, "desc": "Auto turn behavior on map-implied lane change. Default 0."},
      {"type": "int", "param": "AChangeCostStarting", "label": "Lane Change Cost (Start)", "min": 0, "max": 50, "step": 1, "desc": "Extra MPC cost for initiating a lane change. Default 10."},
      {"type": "int", "param": "MapTurnSpeedFactor", "label": "Map Turn Speed Factor", "min": 0, "max": 200, "step": 5, "desc": "Percent multiplier on map-based turn speed targets. Default 90."},
      {"type": "int", "param": "TurnSpeedControlMode", "label": "Turn Speed Control Mode", "min": 0, "max": 2, "step": 1, "desc": "How turn speed control is applied. Default 1."},
      {"type": "separator"},
      {"type": "section", "label": "Curve Speed"},
      {"type": "int", "param": "AutoCurveSpeedFactor", "label": "Curve Speed Factor", "min": 10, "max": 200, "step": 5, "desc": "Percent multiplier on curve speed targets. Default 120."},
      {"type": "int", "param": "AutoCurveSpeedLowerLimit", "label": "Curve Speed Lower Limit", "min": 0, "max": 150, "step": 5, "desc": "Minimum curve speed target (km/h). Default 30."},
      {"type": "separator"},
      {"type": "section", "label": "Cluster / HUD (Extended)"},
      {"type": "bool", "param": "ClusterHud", "label": "Cluster HUD", "default": 0, "desc": "Enable the cluster / HUD render client. Default off."},
      {"type": "int", "param": "ClusterHudBrightness", "label": "Cluster HUD Brightness", "min": 0, "max": 100, "step": 5, "desc": "Cluster HUD brightness (%). Default 0 (auto)."},
      {"type": "int", "param": "ClusterHudCameraViewMode", "label": "Cluster Camera View Mode", "min": 0, "max": 3, "step": 1, "desc": "Cluster camera view mode. Default 0."},
      {"type": "int", "param": "ClusterHudCoreMode", "label": "Cluster Core Mode", "min": 0, "max": 3, "step": 1, "desc": "Cluster core layout mode. Default 0."},
      {"type": "bool", "param": "ClusterHudDebug", "label": "Cluster HUD Debug", "default": 0, "desc": "Show debug overlays on the cluster HUD. Default off."},
      {"type": "bool", "param": "ClusterHudEncoder", "label": "Cluster HUD Encoder", "default": 0, "desc": "Enable the cluster HUD encoder path. Default off."},
      {"type": "int", "param": "ClusterHudLiveFps", "label": "Cluster Live FPS", "min": 1, "max": 60, "step": 1, "desc": "Target render frame rate for live cluster feed. Default 1."},
      {"type": "bool", "param": "ClusterHudMirror", "label": "Cluster Mirror", "default": 0, "desc": "Mirror the cluster HUD horizontally. Default off."},
      {"type": "int", "param": "ClusterHudOrientation", "label": "Cluster Orientation", "min": 0, "max": 3, "step": 1, "desc": "Cluster HUD orientation. Default 0."},
      {"type": "int", "param": "ClusterHudPanelLayout", "label": "Cluster Panel Layout", "min": 0, "max": 3, "step": 1, "desc": "Cluster HUD panel layout. Default 0."},
      {"type": "int", "param": "ClusterHudPriority", "label": "Cluster Priority", "min": 0, "max": 20, "step": 1, "desc": "Cluster HUD process priority. Default 10."},
      {"type": "bool", "param": "ClusterHudRadarDisplay", "label": "Cluster Radar Display", "default": 0, "desc": "Show radar objects on the cluster HUD. Default off."},
      {"type": "int", "param": "ClusterHudRadarInfo", "label": "Cluster Radar Info", "min": 0, "max": 10, "step": 1, "desc": "Cluster radar info detail level. Default 4."},
      {"type": "bool", "param": "ClusterHudRadarSourceColor", "label": "Cluster Radar Source Color", "default": 0, "desc": "Color-code radar source on cluster HUD. Default off."},
      {"type": "int", "param": "ClusterHudScreenMode", "label": "Cluster Screen Mode", "min": 0, "max": 3, "step": 1, "desc": "Cluster HUD screen mode. Default 0."},
      {"type": "int", "param": "ClusterHudTheme", "label": "Cluster Theme", "min": 0, "max": 3, "step": 1, "desc": "Cluster HUD theme. Default 0."},
      {"type": "bool", "param": "ShowCameraWithCluster", "label": "Camera With Cluster", "default": 0, "desc": "Show the camera feed alongside the cluster HUD. Default off."},
      {"type": "int", "param": "ShowCustomBrightness", "label": "Custom Brightness", "min": 0, "max": 100, "step": 5, "desc": "Custom screen brightness (%). Default 100."},
      {"type": "bool", "param": "ShowDateTime", "label": "Show Date/Time", "default": 1, "desc": "Show date and time on the HUD. Default on."},
      {"type": "bool", "param": "ShowDebugUI", "label": "Show Debug UI", "default": 1, "desc": "Show the debug UI overlay. Default on."},
      {"type": "bool", "param": "ShowDeviceState", "label": "Show Device State", "default": 1, "desc": "Show device state on the HUD. Default on."},
      {"type": "bool", "param": "ShowLaneInfo", "label": "Show Lane Info", "default": 1, "desc": "Show lane information on the HUD. Default on."},
      {"type": "bool", "param": "ShowModelView", "label": "Show Model View", "default": 0, "desc": "Show the model path view. Default off."},
      {"type": "int", "param": "ShowPathColor", "label": "Path Color", "min": 0, "max": 20, "step": 1, "desc": "Color used for the planned path. Default 12."},
      {"type": "int", "param": "ShowPathColorCruiseOff", "label": "Path Color (Cruise Off)", "min": 0, "max": 20, "step": 1, "desc": "Path color when cruise is off. Default 1."},
      {"type": "int", "param": "ShowPathColorLane", "label": "Path Color (Lane)", "min": 0, "max": 20, "step": 1, "desc": "Path color in lane mode. Default 3."},
      {"type": "bool", "param": "ShowPathEnd", "label": "Show Path End", "default": 1, "desc": "Show the end of the planned path. Default on."},
      {"type": "int", "param": "ShowPathMode", "label": "Path Mode", "min": 0, "max": 20, "step": 1, "desc": "Path rendering mode. Default 9."},
      {"type": "int", "param": "ShowPathModeLane", "label": "Path Mode (Lane)", "min": 0, "max": 20, "step": 1, "desc": "Path rendering mode in lane mode. Default 11."},
      {"type": "bool", "param": "ShowPlotMode", "label": "Show Plot Mode", "default": 0, "desc": "Show the debug plot overlay. Default off."},
      {"type": "bool", "param": "ShowRadarInfo", "label": "Show Radar Info", "default": 0, "desc": "Show radar information on the HUD. Default off."},
      {"type": "bool", "param": "ShowRouteInfo", "label": "Show Route Info", "default": 0, "desc": "Show route information on the HUD. Default off."},
      {"type": "bool", "param": "ShowTpms", "label": "Show TPMS", "default": 1, "desc": "Show tire pressure (TPMS) on the HUD. Default on."},
      {"type": "bool", "param": "SoftwareMenu", "label": "Software Menu", "default": 0, "desc": "Show the software menu on the HUD. Default off."},
      {"type": "separator"},
      {"type": "section", "label": "Carrot Live (YouTube)"},
      {"type": "bool", "param": "CarrotYouTubeLive", "label": "YouTube Live", "default": 0, "desc": "Stream the driving view to YouTube live. Default off."},
      {"type": "int", "param": "CarrotYouTubeQuality", "label": "YouTube Quality", "min": 0, "max": 3, "step": 1, "desc": "YouTube live stream quality preset. Default 0 (auto)."},
      {"type": "bool", "param": "CarrotYouTubeTimestamp", "label": "YouTube Timestamp", "default": 0, "desc": "Overlay a timestamp on the YouTube live stream. Default off."},
      {"type": "separator"},
      {"type": "section", "label": "Lane Line / ONNX Lane"},
      {"type": "int", "param": "OnnxLaneIntervalMs", "label": "ONNX Lane Interval", "min": 50, "max": 1000, "step": 10, "desc": "ONNX lane-line model inference interval (ms). Default 400."},
      {"type": "int", "param": "OnnxLaneThreshold", "label": "ONNX Lane Threshold", "min": 0, "max": 100, "step": 1, "desc": "ONNX lane-line confidence threshold (%). Default 25."},
      {"type": "separator"},
      {"type": "section", "label": "Steering / Lateral (Extended)"},
      {"type": "int", "param": "AdjustLaneOffset", "label": "Lane Offset Adjust", "min": -50, "max": 50, "step": 1, "desc": "Lateral path offset adjustment (cm). Default 0."},
      {"type": "int", "param": "CameraYawTrimDeg", "label": "Camera Yaw Trim", "min": -20, "max": 20, "step": 1, "desc": "Camera yaw trim (deg). Default 0."},
      {"type": "int", "param": "LatMpcInputOffset", "label": "Lat MPC Input Offset", "min": 0, "max": 20, "step": 1, "desc": "Lateral MPC input offset. Default 4."},
      {"type": "int", "param": "LatSmoothSec", "label": "Lat Smoothing (sec)", "min": 0, "max": 50, "step": 1, "desc": "Lateral path smoothing time constant (x0.1 s). Default 13."},
      {"type": "int", "param": "LateralTorqueAccelFactor", "label": "Lateral Torque Accel Factor", "min": 0, "max": 5000, "step": 50, "desc": "Lateral torque acceleration factor. Default 2500."},
      {"type": "separator"},
      {"type": "section", "label": "Speed Limits / Road Speed"},
      {"type": "int", "param": "AutoNaviSpeedCtrlEnd", "label": "Navi Speed Ctrl End", "min": 0, "max": 30, "step": 1, "desc": "Distance (m) before destination to end navi speed control. Default 7."},
      {"type": "int", "param": "AutoRoadSpeedLimitOffset", "label": "Road Speed Limit Offset", "min": -30, "max": 30, "step": 1, "desc": "Offset applied to the road speed limit (km/h). Default -1 (auto)."},
      {"type": "int", "param": "AutoNaviCountDownMode", "label": "Navi Countdown Mode", "min": 0, "max": 3, "step": 1, "desc": "School-zone / countdown announcement mode. Default 2."},
      {"type": "int", "param": "AutoNaviSpeedBumpSpeed", "label": "Speed Bump Target Speed", "min": 0, "max": 100, "step": 5, "desc": "Target speed (km/h) over a speed bump. Default 35."},
      {"type": "int", "param": "AutoNaviSpeedBumpTime", "label": "Speed Bump Time", "min": 0, "max": 10, "step": 1, "desc": "Virtual speed-bump deceleration time (x0.1 s). Default 1."},
      {"type": "separator"},
      {"type": "section", "label": "Vehicle / Car Features"},
      {"type": "bool", "param": "DisableDM", "label": "Disable Driver Monitoring", "default": 0, "desc": "Disable driver monitoring (LITE-style). Default off."},
      {"type": "bool", "param": "DisableMinSteerSpeed", "label": "Disable Min Steer Speed", "default": 0, "desc": "Disable the minimum steering speed gate. Default off."},
      {"type": "bool", "param": "HyundaiCameraSCC", "label": "Hyundai Camera SCC", "default": 0, "desc": "Use camera-based SCC on Hyundai platforms. Default off."},
      {"type": "bool", "param": "IsLdwsCar", "label": "LDWS Car", "default": 0, "desc": "Vehicle has a lane departure warning system. Default off."},
      {"type": "bool", "param": "HDPuse", "label": "HD Pause", "default": 0, "desc": "Pause control in high-definition map mode. Default off."},
      {"type": "bool", "param": "HotspotOnBoot", "label": "Hotspot On Boot", "default": 0, "desc": "Start a Wi-Fi hotspot on boot. Default off."},
      {"type": "int", "param": "MapboxStyle", "label": "Mapbox Style", "min": 0, "max": 3, "step": 1, "desc": "Mapbox map style preset. Default 0."},
      {"type": "int", "param": "MaxAngleFrames", "label": "Max Angle Frames", "min": 0, "max": 200, "step": 1, "desc": "Maximum steering-angle stabilization frames. Default 89."},
      {"type": "int", "param": "MaxTimeOffroadMin", "label": "Max Time Offroad (min)", "min": 0, "max": 600, "step": 5, "desc": "Maximum offroad time before shutdown (minutes). Default 60."},
      {"type": "bool", "param": "RecordRoadCam", "label": "Record Road Cam", "default": 0, "desc": "Record the road camera. Default off."},
      {"type": "bool", "param": "ShareData", "label": "Share Data", "default": 0, "desc": "Share anonymous driving data. Default off."},
      {"type": "bool", "param": "UseWideCamera", "label": "Use Wide Camera", "default": 1, "desc": "Use the wide camera for vision. Default on."},
      {"type": "bool", "param": "MuteDoor", "label": "Mute Door", "default": 0, "desc": "Mute door-open chime. Default off."},
      {"type": "bool", "param": "MuteSeatbelt", "label": "Mute Seatbelt", "default": 0, "desc": "Mute seatbelt chime. Default off."},
      {"type": "bool", "param": "EnableCornerRadar", "label": "Enable Corner Radar", "default": 0, "desc": "Enable corner radar processing. Default off."},
      {"type": "bool", "param": "EnableRadarTracks", "label": "Enable Radar Tracks", "default": 0, "desc": "Enable radar track fusion. Default off."},
      {"type": "bool", "param": "EnableSpeedTF", "label": "Enable Speed TF", "default": 0, "desc": "Enable speed time-to-event fusion. Default off."},
      {"type": "text", "param": "SoundLanguageSetting", "label": "Sound Language",
       "desc": "Sound/voice language setting (e.g. auto, en, ko). Default auto."},
      {"type": "separator"},
      {"type": "section", "label": "Driving Mode / Lights"},
      {"type": "int", "param": "MyDrivingMode", "label": "My Driving Mode", "min": 0, "max": 3, "step": 1, "desc": "Carrot driving style preset (0=eco,1=normal,2=sport,3=safe). Default 3."},
      {"type": "int", "param": "TrafficLightDetectMode", "label": "Traffic Light Detect Mode", "min": 0, "max": 2, "step": 1, "desc": "Traffic-light assist mode (0=off,1=red stop,2=+green go). Default 2."},
      {"type": "separator"},
      {"type": "section", "label": "Developer"},
      {"type": "bool", "param": "CanfdDebug", "label": "CAN-FD Debug", "default": 0, "desc": "Enable CAN-FD debug logging. Default off."},
      {"type": "bool", "param": "CanfdHDA2", "label": "CAN-FD HDA2", "default": 0, "desc": "CAN-FD HDA2 variant. Default off."},
      {"type": "bool", "param": "HardwareC3xLite", "label": "Hardware C3x Lite", "default": 0, "desc": "C3x Lite hardware variant. Default off."},
      {"type": "bool", "param": "CruiseButtonTest1", "label": "Cruise Button Test 1", "default": 0, "desc": "Cruise button test hook 1. Default off."},
      {"type": "bool", "param": "CruiseButtonTest2", "label": "Cruise Button Test 2", "default": 0, "desc": "Cruise button test hook 2. Default off."},
      {"type": "bool", "param": "CruiseButtonTest3", "label": "Cruise Button Test 3", "default": 0, "desc": "Cruise button test hook 3. Default off."},
      {"type": "bool", "param": "CarrotTireTrajectory", "label": "Tire Trajectory", "default": 0, "desc": "Render tire trajectory debug overlay. Default off."},
            {"type": "action", "action": "carrot_tuning_reset", "label": "Reset Carrot Tuning", "button": "RESET",
       "confirm": "Reset all Carrot tuning parameters to defaults?",
       "desc": "Restore every Carrot tuning parameter on this page to its compiled-in default."},
    ],
  },
  "steering__mads": {
    "id": "steering__mads",
    "title": "Customize MADS",
    "parent": "steering",
    "widgets": [
      {"type": "bool", "param": "MadsMainCruiseAllowed", "label": "Toggle with Main Cruise"},
      {"type": "bool", "param": "MadsUnifiedEngagementMode", "label": "Unified Engagement Mode (UEM)"},
      {"type": "multiple_button", "param": "MadsSteeringMode", "label": "Steering Mode on Brake Pedal",
       "buttons": ["Remain Active", "Pause", "Disengage"]},
    ],
  },
  "steering__lane_change": {
    "id": "steering__lane_change",
    "title": "Customize Lane Change",
    "parent": "steering",
    "widgets": [
      {"type": "option", "param": "AutoLaneChangeTimer", "label": "Auto Lane Change by Blinker",
       "min": -1, "max": 5, "step": 1, "label_format": "lane_change_timer", "layout": "stacked",
       "desc": "Set a timer to delay the auto lane change operation when the blinker is used. "
               "No nudge on the steering wheel is required to auto lane change if a timer is set. Default is Nudge. "
               "Please use caution when using this feature. Only use the blinker when traffic and road conditions permit."},
      {"type": "separator"},
      {"type": "bool", "param": "AutoLaneChangeBsmDelay", "label": "Auto Lane Change: Delay with Blind Spot",
       "desc": "Toggle to enable a delay timer for seamless lane changes when blind spot monitoring (BSM) "
               "detects a obstructing vehicle, ensuring safe maneuvering."},
      {"type": "separator"},
      {"type": "bool", "param": "RoadEdgeLaneChangeEnabled", "label": "Block Lane Change: Road Edge Detection",
       "desc": "Blocks the lane change if the model sees a road edge on your signaled side."},
    ],
  },
  "steering__torque": {
    "id": "steering__torque",
    "title": "Customize Torque Params",
    "parent": "steering",
    "widgets": [
      {"type": "bool", "param": "LateralJerkTorqueController", "label": "Lateral Jerk Torque Controller", "offroad_only": True,
       "desc": "Looks ahead at planned steering to reduce sudden corrections, so the wheel moves more smoothly through turns. Works with Self-Tune and custom tuning. Thanks to @twilsonco for the implementation."},
      {"type": "action", "action": "torque_tune_version", "label": "Torque Control Tune Version", "button": "SELECT",
       "desc": "Select the version of Torque Control Tune to use."},
      {"type": "bool", "param": "LiveTorqueParamsToggle", "label": "Self-Tune", "offroad_only": True,
       "desc": "Enables self-tune for Torque lateral control for platforms that do not use Torque lateral control by default."},
      {"type": "bool", "param": "LiveTorqueParamsRelaxedToggle", "label": "Less Restrict Settings for Self-Tune (Beta)",
       "desc": "Less strict settings when using Self-Tune. This allows torqued to be more forgiving when learning values.",
       "visible_if": {"param": "LiveTorqueParamsToggle", "eq": "1"}, "offroad_only": True},
      {"type": "bool", "param": "CustomTorqueParams", "label": "Enable Custom Tuning", "offroad_only": True,
       "desc": "Enables custom tuning for Torque lateral control. Modifying Lateral Acceleration Factor and Friction below will override the offline values indicated in the YAML files within \"opendbc/car/torque_data\". The values will also be used live when \"Manual Real-Time Tuning\" toggle is enabled."},
      {"type": "bool", "param": "TorqueParamsOverrideEnabled", "label": "Manual Real-Time Tuning",
       "desc": "Enforces the torque lateral controller to use the fixed values instead of the learned values from Self-Tune. Enabling this toggle overrides Self-Tune values.",
       "visible_if": {"param": "CustomTorqueParams", "eq": "1"}, "offroad_only": True},
      {"type": "option", "param": "TorqueParamsOverrideLatAccelFactor", "label": "Lateral Acceleration Factor",
       "min": 1, "max": 500, "step": 1, "label_format": "torque_lat_accel",
       "visible_if": {"param": "CustomTorqueParams", "eq": "1"}},
      {"type": "option", "param": "TorqueParamsOverrideFriction", "label": "Friction",
       "min": 1, "max": 100, "step": 1, "label_format": "torque_friction",
       "visible_if": {"param": "CustomTorqueParams", "eq": "1"}},
    ],
  },
  "cruise__sla": {
    "id": "cruise__sla",
    "title": "Speed Limit",
    "parent": "cruise",
    "widgets": [
      {"type": "multiple_button", "param": "SpeedLimitMode", "label": "Speed Limit",
       "buttons": ["Off", "Info", "Warning", "Assist"]},
      {"type": "custom", "custom": "speed_limit_sources", "label": "Speed Limit Sources",
       "desc": "Real-time values from the car (TSR), map provider (OSM/Amap), and Carrot navigation. The merged value is what the Speed Limit widget currently displays."},
      {"type": "custom", "custom": "longitudinal_source", "label": "Longitudinal Source",
       "desc": "Which longitudinal plan source is currently winning the arbitration: cruise, sccVision, sccMap, speedLimitAssist, or carrot."},
      {"type": "custom", "custom": "traffic_light_fusion", "label": "Traffic Light Fusion",
       "desc": "Fused traffic-light state from Carrot/Amap navigation and vision stop-line detection."},
      {"type": "subpanel", "target": "cruise__sla__policy", "label": "Customize Source", "button": "CUSTOMIZE"},
      {"type": "multiple_button", "param": "SpeedLimitOffsetType", "label": "Speed Limit Offset",
       "buttons": ["None", "Fixed", "%"]},
      {"type": "option", "param": "SpeedLimitValueOffset", "label": "Offset Value",
       "min": -30, "max": 30, "step": 1, "label_format": "speed_limit_offset",
       "visible_if": {"param": "SpeedLimitOffsetType", "ne": "0"}},
    ],
  },
  "cruise__sla__policy": {
    "id": "cruise__sla__policy",
    "title": "Speed Limit Source",
    "parent": "cruise__sla",
    "widgets": [
      {"type": "multiple_button", "param": "SpeedLimitPolicy", "label": "Speed Limit Source",
       "buttons": ["Car Only", "Map Only", "Car First", "Map First", "Combined"]},
    ],
  },
  "network__advanced": {
    "id": "network__advanced",
    "title": "Advanced Network",
    "parent": "network",
    "custom": "network_advanced",
    "widgets": [
      {"type": "bool", "param": "GsmRoaming", "label": "Enable Roaming"},
      {"type": "bool", "param": "GsmMetered", "label": "Cellular Metered",
       "desc": "Prevent large data uploads when on a metered cellular connection"},
    ],
  },
  "cruise__longitudinal_mpc_tuning": {
    "id": "cruise__longitudinal_mpc_tuning",
    "title": "Longitudinal MPC Tuning",
    "parent": "cruise",
    "custom": "longitudinal_mpc_tuning",
    "widgets": [],
  },
}


def panel_ids() -> list[str]:
  return [p["id"] for p in PANELS]


def get_panel(panel_id: str) -> dict[str, Any] | None:
  if panel_id in SUBPANELS:
    return SUBPANELS[panel_id]
  for p in PANELS:
    if p["id"] == panel_id:
      return p
  return None


def panel_schema() -> dict[str, Any]:
  from webui.server.bridge.design_tokens import PANEL_ICONS, tokens_payload
  from webui.server.bridge.headless_util import is_headless_mode
  from webui.server.bridge.lite_util import is_lite_hw, should_hide_widget

  headless = is_headless_mode()
  lite = is_lite_hw()
  headless_hide_params = {
    "Brightness", "OnroadScreenOffBrightness", "OnroadScreenOffTimer",
    "InteractivityTimeout", "ScreenSaverEnabled", "ScreenSaverTimeout",
  }

  def _filter_widgets(widgets: list[dict]) -> list[dict]:
    out = []
    for w in widgets:
      if should_hide_widget(w):
        continue
      if headless and w.get("param") in headless_hide_params:
        continue
      if w.get("type") == "separator" and out and out[-1].get("type") == "separator":
        continue
      out.append(w)
    return out

  panels_out = []
  for p in PANELS:
    entry = {**p, "icon": PANEL_ICONS.get(p["id"], "")}
    widgets = _filter_widgets(list(entry.get("widgets") or []))
    if headless and p.get("id") == "display":
      entry["headless_note"] = "Built-in display settings are hidden on headless devices."
      widgets.insert(0, {
        "type": "html",
        "i18n_key": "No built-in screen — brightness and screen saver do not apply. Camera stream settings below are used by Web UI.",
      })
      widgets.insert(1, {"type": "separator"})
    entry["widgets"] = widgets
    panels_out.append(entry)
  return {
    "ok": True,
    "panels": panels_out,
    "subpanels": list(SUBPANELS.keys()),
    "headless": headless,
    "lite": lite,
    **tokens_payload(),
  }


def panel_param_keys(panel_id: str) -> list[str]:
  panel = get_panel(panel_id)
  if not panel:
    return []
  keys: list[str] = []
  for w in panel.get("widgets", []):
    for dep_key in ("visible_if", "advanced_if"):
      dep = w.get(dep_key)
      if isinstance(dep, dict) and dep.get("param"):
        keys.append(dep["param"])
    if w.get("type") == "dual_button":
      for side in ("left", "right"):
        sk = (w.get(side) or {}).get("param")
        if sk:
          keys.append(sk)
      continue
    key = w.get("param")
    if key:
      keys.append(key)
  return sorted(set(keys))
